apiVersion: apps/v1
kind: Deployment
metadata:
  name: spc-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spc-argocd
      version: "9"
  template:
    metadata:
      labels:
        app: spc-argocd
        version: "9"
    spec:
      containers:
      - name: spc-deployment
        image: pkkanumuri/spc:spc-9
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080